name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show directory contents
        run: |
          echo "Current working directory: $(pwd)"
          ls -al

      - name: Build Docker image (local test)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api:latest -f Dockerfile .

      - name: Tag and push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api:0.0.1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api:0.0.1

      - name: Tag and push to GHCR
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api:latest ghcr.io/${{ github.repository_owner }}/sysinfo-api:latest
          docker push ghcr.io/${{ github.repository_owner }}/sysinfo-api:latest
